var huntDiscount = angular.module('huntDiscount', []);

huntDiscount.controller('ProductListCtrl', function ($scope){
	$scope.products = [
		{
		'name': 'Hair & Makeup Services',
			'color': 'Red',
			'brand': 'Sony Ericsson',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://discount-coupon-codes.upto75.com/uploadimages/coupons/5147-VLC.jpg'
		},
		/*2nd product*/
		{
		'name': 'Bageecha Restaurant',
			'color': '',
			'brand': '',
			'discount': '15% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': '#87, OLD NO 87/42, CHINNAPANAHALLI OUTER RING ROAD,BANGALORE',
			'end': '31-Dec-2014',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://discount-coupon-codes.upto75.com/uploadimages/sales_offer_mainpic_20110603130759Bageecha_500x200_Banner.png'
		},
		{
		'name': 'Hair & Makeup Services',
			'color': 'Red',
			'brand': 'Sony Ericsson',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://discount-coupon-codes.upto75.com/uploadimages/vendor_logo_20101022130329Vibes_Logo_thumb.png'
		},
		/*2nd product*/
		{
		'name': 'Bageecha Restaurant',
			'color': '',
			'brand': '',
			'discount': '15% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://discount-coupon-codes.upto75.com/uploadimages/sales_offer_mainpic_20110603130759Bageecha_500x200_Banner.png'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://discount-coupon-codes.upto75.com/uploadimages/coupons/5814-Batras_5814.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://discount-coupon-codes.upto75.com/uploadimages/sales_offer_mainpic_20110826173547NMMedicalCenter_Banner.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		},
		{
		'name': 'BlackBerry Z10',
			'color': 'Charcoal Black',
			'brand': 'BlackBerry',
			'discount': '68% off',
			'price': '13,700',
			'seller': 'ebay.in',
			'location': 'NA',
			'end': 'NA',
			'tag': 'Mobile',
			'category': 'Electronics',
			'link': 'http://www.ebay.in/sch/Mobile-Phones-/15032/i.html?_sop=15&LH_BIN=1&_from&Colour=Black&LH_ItemCondition=3&_mPrRngCbx=1&_udlo=9000&_udhi&Model=Blackberry%2520Z10&Brand=Blackberry&Capacity=16%2520GB&_nkw=BlackBerry%20Z10&_dcat=15032&rt=nc&_pppn=r1&Sim%2520Type=Single%2520Sim',
			'image': 'http://global.blackberry.com/content/dam/blackBerry/images/device/smartphone/blackberry-10/z10/product/gallery/large-360.jpg.original.jpg'
		}
	];
});